### ISSUE TITLE
Backslashes are not converted to directories on Unix-like systems

### ISSUE THREAD

**Issue by Teteros** [Phrohdoh/easage#2]
BIG archives made on Windows currently do not retain directory trees on Unix-like machines.
Backslashes `\` are not converted to directories `/` (on e.g. linux) essentially.

# Test case:
On Windows
```cmd
mkdir foo & echo baz >foo\bar & easage pack --source foo --output foo.big
```
On Linux
```
easage list foo.big
Archive:
  kind: Big4
  size: 50
  len: 1
  data start: 0x2b
Entries:
  foo\bar
    offset: 0x2b
    len: 7
```
```sh
└> easage extract --output . --source foo.big
└> ls -la
total 8
drwxr-xr-x  2 tete tete  80 Oct 23 13:34  .
drwxrwxrwt 10 root root 320 Oct 23 13:33  ..
-rw-r--r--  1 tete tete   7 Oct 23 13:34 'foo\bar'
-rw-r--r--  1 tete tete  50 Oct 23 13:27  foo.big
```
## Expected: `foo/bar`
i.e. `bar` in folder called `foo`

## The opposite works however
`BIG` archives created on Linux with `easage pack` will extract on Windows machines with folder paths respected.

# `foo.big` with `\` paths attached below
(wrapped in .zip due to github attachment support)
[foo.big.zip](https://github.com/Phrohdoh/easage/files/1407107/foo.big.zip)
