### ISSUE TITLE
Cut down on the noise that easage-list generates

### ISSUE THREAD

**Issue by phrohdoh** [Phrohdoh/easage#21]
`easage list` is quite noisy at the moment.

Planned changes:
 - [ ] Introduce a `--verbose` flag
 - [ ] Output only entry names if the verbose flag *is not present*
 - [ ] Output the currently-outputted information if the verbose flag *is present*

For reference this is what `easage list` currently produces on a test BIG archive I have locally:

```
Archive:
  kind: BigF
  size: 218
  len: 2
  data start: 0x36
Entries:
  test/b.txt
    offset: 0x36
    len: 20
  test/a.txt
    offset: 0x4a
    len: 144
```
